Stop on errors in _includes.sh
acquia/orca pull request #153
Opened 2021-09-21 18:56 UTC by danepowell

Katherine and I completely missed a syntax error while working _includes.sh, because Bash doesn't exit immediately upon errors.

@TravisCarden do you recall why you only `set -e` at the _end_ of _includes.sh, rather than the beginning?

2021-09-21 20:11 UTC, danepowell commented
The failing test isn't related to this PR.

I think we need to address the failing test. It's "allowed" to fail and won't block merging this PR, but will inevitably cause confusion (I hate the red 'x').

It's failing because of the ACMS transition. I pinged Travis with details in Slack. We'd either need to fix the test so it passes (i.e. stop scanning failing contrib modules), or disable it.

2021-09-22 18:01 UTC, danepowell commented
Regarding the test failures, we're going to try to fix the failing tests. For the live job, I've opened https://github.com/acquia/orca/pull/154 . For the deprecated code scan, we decided isolated tests should only include the SUT as a dependency, and therefore should use the minimal project template. Since the minimal project template contains no failing code, this should pass again.

SUTs that do have deprecated code will see failures in their own isolated tests. This is perhaps an improvement over Travis CI, which swept these failures under the rug by not marking the whole job as failed. Note that this is a "soft" failure, it won't block PR merges.

2021-09-24 18:24 UTC, TravisCarden requested changes
@danepowell, I moved the whole line (`set -ev`) to the bottom of `_includes.sh` so as not to needlessly print the whole contents of the file each of the (many) times it gets executed on every build. But looking at it again, there's no reason to move both switches together. Let's have our cake and eat it, too. 😉

2021-09-24 18:24 UTC, TravisCarden commented on bin/ci/_includes.sh
> +set -ev
```suggestion
# Exit as soon as one command returns a non-zero exit code.
set -e
```

2021-09-24 18:24 UTC, TravisCarden commented on bin/ci/_includes.sh
> -set -ev
```diff
- # Exit as soon as one command returns a non-zero exit code and make the shell
- # print all lines in the script before executing them.
- set -ev
+ # Make the shell print all lines in the script before executing them.
+ set -v
```

2021-09-25 16:36 UTC, TravisCarden approved these changes

2021-09-25 16:37 UTC, merged