ORCA-96: Domo Integration
acquia/orca pull request #350
Opened 2023-03-24 16:16 UTC by secretsayan

2023-06-12 15:13 UTC, TravisCarden requested changes
Just a few changes.

2023-06-13 17:37 UTC, secretsayan commented on src/Domain/Composer/Version/DrupalCoreVersionResolver.php
> +      $this->nextMajorLatestMinorBetaOrLater = NULL;
Please suggest a function name for the same :)

2023-06-13 18:47 UTC, TravisCarden approved these changes

2023-06-13 19:11 UTC, merged

2023-08-22 21:11 UTC, danepowell commented
@secretsayan @TravisCarden it looks like the ORCA workflow example integration was never updated to add these new secrets. Was that intentional? https://github.com/acquia/orca/blob/develop/example/.github/workflows/orca.yml

2023-08-28 08:05 UTC, secretsayan commented
@danepowell Thanks for pointing this out. PR https://github.com/acquia/orca/pull/425 created to modify example files.